# Generated by Django 4.2.7 on 2023-11-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eamil_address',
            new_name='email_address',
        ),
    ]
