# Generated by Django 4.2.7 on 2023-12-03 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='wall_app.messages'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='wall_app.users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='masssege',
            field=models.TextField(null=True),
        ),
    ]
