# Generated by Django 4.2.7 on 2023-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
